import { store } from './services/appStore.js';
import { vesselService, cameraService, incidentService, securityService } from './services/services.js';
import { simulationEngine } from './simulation/simulationEngine.js';
import { scenarioDefinitions } from './data/mock.js';

const navigation = ['Dashboard', 'Fleet', 'Vessels', 'Cameras', 'Cybersecurity', 'Incidents', 'Sensors', 'Access Control', 'Reports', 'Settings'];
const filters = { vessel: 'all', severity: 'all', category: 'all' };
let searchTerm = '';
const escape = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
const vesselName = id => vesselService.getById(id)?.name || 'Unknown vessel';
const severityClass = value => ['CRITICAL', 'HIGH'].includes(value) ? 'red' : ['MEDIUM', 'WARNING'].includes(value) ? 'amber' : '';

function layout(content) {
  const unread = store.notifications.filter(note => !note.read).length;
  document.querySelector('#app').innerHTML = `<div class="app"><aside class="sidebar"><div class="brand"><div class="brand-mark">S</div><div><strong>SEASHIELD</strong><small>MARITIME SECURITY OS</small></div></div><div class="nav-label">OPERATIONS</div><nav class="nav">${navigation.map(label => `<button class="${store.active === label ? 'active' : ''}" data-nav="${label}"><span class="nav-icon">◈</span><span>${label}</span></button>`).join('')}</nav><div class="sidebar-bottom"><div class="edge"><i class="dot"></i> EDGE SIMULATOR <span style="margin-left:auto;color:#5b7a83">V1.0.4</span></div><div class="sidebar-footer">Last sync ${new Date().toISOString().slice(11, 19)} UTC<br/>Simulation mode enabled</div></div></aside><main class="main"><header class="topbar"><div class="top-title">OPERATIONS CENTER <span>/ ${store.active.toUpperCase()}</span></div><select class="selector" id="vessel-select"><option value="all">All vessels</option>${store.vessels.map(vessel => `<option value="${vessel.id}" ${store.selectedVessel === vessel.id ? 'selected' : ''}>${vessel.name}</option>`).join('')}</select><input class="search" id="search" placeholder="Search events, vessels..." /><button class="top-action" id="notify">♧<b class="badge">${unread}</b></button><div class="user"><div class="avatar">JD</div><div>J. Dawson<small>SECURITY OPERATOR</small></div></div></header><section class="content">${content}</section></main></div>`;
  bind();
}

function heading(title, description, eyebrow = 'MODULE // SIMULATION MODE') { return `<div class="heading-row"><div><div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p>${description}</p></div><div class="time">03 SEP 2026 · ${new Date().toISOString().slice(11, 19)} UTC</div></div>`; }
function kpi(label, value, sub, color) { return `<div class="kpi" style="--accent:var(${color})"><div class="kpi-head"><span>${label}</span><span class="kpi-icon">◈</span></div><div class="kpi-value">${value}</div><div class="kpi-sub">${sub}</div></div>`; }
function timeline() {
  const events = store.events.filter(event => (filters.vessel === 'all' || event.vesselId === filters.vessel) && (filters.severity === 'all' || event.severity === filters.severity) && (filters.category === 'all' || event.category === filters.category) && (!searchTerm || `${event.description} ${event.source} ${vesselName(event.vesselId)}`.toLowerCase().includes(searchTerm.toLowerCase())));
  return `<section class="panel"><div class="filter-row"><select id="filter-vessel"><option value="all">All vessels</option>${store.vessels.map(vessel => `<option value="${vessel.id}">${vessel.name}</option>`).join('')}</select><select id="filter-severity"><option value="all">All severity</option>${['INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL'].map(value => `<option>${value}</option>`).join('')}</select><select id="filter-category"><option value="all">All categories</option>${['PHYSICAL', 'CYBER', 'VESSEL_SYSTEM'].map(value => `<option>${value}</option>`).join('')}</select></div><div class="events">${events.length ? events.map(event => `<div class="event"><time>${escape(event.timestamp)}</time><i class="event-marker" style="--accent:var(--${severityClass(event.severity) === 'red' ? 'red' : severityClass(event.severity) === 'amber' ? 'amber' : 'cyan'})"></i><div><strong>${escape(event.description)}</strong><p>${vesselName(event.vesselId)} · ${event.category} · ${event.source}</p></div><span class="tag ${severityClass(event.severity)}">${event.severity}</span></div>`).join('') : '<div class="empty-state">No events match the selected filters.</div>'}</div></section>`;
}
function incidents() {
  const records = incidentService.getAll();
  return `<section class="panel"><div class="events">${records.length ? records.map(incident => `<div class="event incident-row"><time>${incident.incidentId}</time><i class="event-marker" style="--accent:var(--${severityClass(incident.severity) || 'amber'})"></i><div><strong>${escape(incident.title)}</strong><p>${vesselName(incident.vesselId)} · ${incident.affectedSystems.join(', ')}</p></div><select class="incident-status" data-incident="${incident.incidentId}">${['NEW', 'INVESTIGATING', 'CONTAINED', 'RESOLVED', 'FALSE POSITIVE'].map(status => `<option ${incident.status === status ? 'selected' : ''}>${status}</option>`).join('')}</select></div>`).join('') : '<div class="empty-state">No incidents. The simulation is quiet.</div>'}</div></section>`;
}
function dashboard() {
  const status = securityService.getFleetStatus();
  const active = incidentService.getAll().filter(incident => !['RESOLVED', 'FALSE POSITIVE'].includes(incident.status));
  const cyber = store.events.filter(event => event.category === 'CYBER' && event.status !== 'RESOLVED').length;
  const average = Math.round(store.vessels.reduce((sum, vessel) => sum + vessel.score, 0) / store.vessels.length);
  return heading('Security overview', 'Fleet-wide maritime security telemetry and incident awareness.', 'LIVE OPERATIONS // SIMULATION MODE') + `<div class="kpis">${kpi('Fleet security', `${average}%`, `${status.SECURE} secure · ${status.WARNING} warning · ${status.CRITICAL} critical`, '--green')}${kpi('Vessels monitored', `${store.vessels.length} / ${store.vessels.length}`, 'Edge gateways reporting', '--cyan')}${kpi('Cameras online', `${store.cameras.filter(camera => camera.online).length} / ${store.cameras.length}`, 'Simulated availability', '--blue')}${kpi('Active incidents', active.length, 'Calculated from state', '--red')}${kpi('Cyber alerts', cyber, 'Open simulated events', '--amber')}</div><div class="section-label">FLEET TELEMETRY</div><div class="dashboard-grid"><section class="panel"><div class="panel-header"><h2>Fleet security posture</h2><span>CALCULATED FROM STATE</span></div>${store.vessels.map(vessel => `<div class="status-line"><span class="label">${vessel.name}</span><div class="track"><i style="width:${vessel.score}%;background:var(--${vessel.status === 'CRITICAL' ? 'red' : vessel.status === 'WARNING' ? 'amber' : 'green'})"></i></div><b>${vessel.score}</b></div>`).join('')}</section>${scenarioPanel()}</div><div class="section-label">GLOBAL EVENT TIMELINE</div>${timeline()}<div class="section-label">INCIDENT QUEUE</div>${incidents()}`;
}
function scenarioPanel() { return `<section class="panel"><div class="panel-header"><h2>Demo scenario</h2><span>${store.scenario.status}</span></div><div class="scenario-controls"><select id="scenario-select">${Object.entries(scenarioDefinitions).map(([key, value]) => `<option value="${key}">${value.name}</option>`).join('')}</select>${['start', 'pause', 'resume', 'stop', 'reset'].map(action => `<button class="trigger" data-scenario="${action}">${action[0].toUpperCase() + action.slice(1)}</button>`).join('')}</div><div class="sim-note"><b>${store.scenario.name || 'Ready for demonstration'}</b><br/>Events appear sequentially and can create correlated incidents.</div></section>`; }
function moduleView() {
  const data = store.active === 'Cameras' ? store.cameras.map(camera => [camera.location, camera.online ? 'ONLINE' : 'OFFLINE', `${camera.id.toUpperCase()} · ${vesselName(camera.vesselId)} · ${camera.recording ? 'Recording' : 'Not recording'}`]) : store.active === 'Fleet' || store.active === 'Vessels' ? store.vessels.map(vessel => [vessel.name, vessel.status, `${vessel.imo} · Security score ${vessel.score}/100`]) : store.active === 'Incidents' ? incidentService.getAll().map(incident => [incident.incidentId, incident.status, `${incident.title} · ${vesselName(incident.vesselId)}`]) : store.active === 'Cybersecurity' ? [['Unknown devices', store.events.filter(event => event.eventType === 'UNKNOWN_DEVICE_DETECTED').length, 'Network Monitor'], ['Failed authentication', store.events.filter(event => event.eventType === 'FAILED_AUTHENTICATION').length, 'Identity Gateway'], ['Firewall blocks', store.events.filter(event => event.eventType === 'FIREWALL_BLOCK').length, 'Policy enforcement']] : store.active === 'Sensors' ? [['Online sensors', store.sensors.filter(sensor => sensor.online).length, `${store.sensors.length} provisioned`], ['Fire / smoke', 'NOMINAL', 'All vessels'], ['Water / bilge', 'NOMINAL', 'All vessels']] : store.active === 'Access Control' ? store.accessEvents.map(event => [event.type, event.area, `${vesselName(event.vesselId)} · ${event.actor}`]) : store.active === 'Reports' ? [['Events processed', store.events.length, 'Global timeline'], ['Active incidents', incidentService.getAll().filter(incident => !['RESOLVED', 'FALSE POSITIVE'].includes(incident.status)).length, 'Requires attention'], ['Fleet score', `${Math.round(store.vessels.reduce((sum, vessel) => sum + vessel.score, 0) / store.vessels.length)}%`, 'Calculated average']] : [['Runtime', 'Desktop prototype', 'Simulation mode enabled'], ['Data source', 'Local mock services', 'No vessel connection'], ['API boundary', 'Reserved', 'FastAPI compatible']];
  return heading(store.active, `Operational ${store.active.toLowerCase()} data from shared simulation state.`) + `<div class="section-label">${store.active.toUpperCase()} TELEMETRY</div><div class="module-grid">${data.map(row => `<section class="panel module-card"><div class="panel-header"><h2>${escape(row[0])}</h2><span class="tag ${severityClass(row[1])}">${escape(row[1])}</span></div><p>${escape(row[2])}</p><div class="module-bar"><i style="width:${String(row[1]).includes('OFFLINE') ? 30 : 94}%"></i></div>${store.active === 'Incidents' ? `<select class="incident-status" data-incident="${row[0]}">${['NEW', 'INVESTIGATING', 'CONTAINED', 'RESOLVED', 'FALSE POSITIVE'].map(status => `<option ${row[1] === status ? 'selected' : ''}>${status}</option>`).join('')}</select>` : ''}</section>`).join('')}</div><div class="sim-note"><b>Prototype boundary</b><br/>All values are fictional simulation output. Real vessel, CCTV, network, and FastAPI connections are reserved for a future version.</div>`;
}
function render() { layout(store.active === 'Dashboard' ? dashboard() : moduleView()); }
function bind() {
  document.querySelectorAll('[data-nav]').forEach(button => button.addEventListener('click', () => { store.active = button.dataset.nav; render(); }));
  document.querySelector('#vessel-select')?.addEventListener('change', event => { store.selectedVessel = event.target.value; render(); });
  document.querySelector('#search')?.addEventListener('input', event => { searchTerm = event.target.value; if (store.active === 'Dashboard') render(); });
  document.querySelector('#notify')?.addEventListener('click', () => { const messages = store.notifications.length ? store.notifications.map(note => `${note.severity}: ${note.title}`).join('\n') : 'No notifications.'; store.markNotificationsRead(); alert(messages); });
  document.querySelectorAll('[data-scenario]').forEach(button => button.addEventListener('click', () => { try { const action = button.dataset.scenario; action === 'start' ? simulationEngine.start(document.querySelector('#scenario-select').value) : simulationEngine[action](); } catch (error) { alert(`Simulation error: ${error.message}`); } }));
  document.querySelectorAll('.incident-status').forEach(select => select.addEventListener('change', event => incidentService.updateStatus(select.dataset.incident, event.target.value)));
  ['vessel', 'severity', 'category'].forEach(key => document.querySelector(`#filter-${key}`)?.addEventListener('change', event => { filters[key] = event.target.value; render(); }));
}
store.subscribe(render);
render();